### PR TITLE
Update to new stable `#![doc = include_str!]`

### PR DESCRIPTION
**Pull request by delta1**
Hi folks! We're trying to move to stable rust so I thought I'd contribute this change upstream :) 

Removes `feature(external_doc)` in favor of `#![doc = include_str!]` introduced in stable Rust 1.54. 

Fixed up the tests imports and bumped the version - I understand you may not want these changes but thought I'd offer them for now! 

Cheers

### CODE REVIEW

**Review by hdevalence — APPROVED** [review]
Thanks!

**Comment by hdevalence** [comment]
Closes #2 (probably)

**Comment by hdevalence** [comment]
I'd like to fix #1 before merging this just to have some checks in place, but otherwise this looks good to go!

**Comment by delta1** [comment]
> I'd like to fix #1 before merging this just to have some checks in place, but otherwise this looks good to go!

Cool! I’m happy to submit a workflow file if you like?

**Comment by hdevalence** [comment]
Sure! If not, I'll get to it this weekend.

**Comment by delta1** [comment]
I might only have time on Monday but will try find a gap 👍

**Comment by delta1** [comment]
Hi @hdevalence I added a github actions workflow that should mirror what travis ci was doing, example run here: https://github.com/delta1/subtle-ng/actions/runs/1203724120

**Comment by hdevalence** [comment]
Awesome, thanks!

**Pull request merged**
